<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="TestConfig.fs" />
    <Compile Include="PostgresFixture.fs" />
    <Compile Include="SmokeTests.fs" />
    <Compile Include="Phase1Tests.fs" />
    <Compile Include="Phase2Tests.fs" />
    <Compile Include="Phase3Tests.fs" />
    <Compile Include="Phase4Tests.fs" />
    <Compile Include="Phase5Tests.fs" />
    <Compile Include="Phase6Tests.fs" />
    <Compile Include="Phase7Tests.fs" />
    <Compile Include="Phase9Tests.fs" />
    <Compile Include="Phase10Tests.fs" />
    <Compile Include="Phase11Tests.fs" />
    <Compile Include="Phase12Tests.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Fspg/Fspg.fsproj" />
  </ItemGroup>

</Project>
